### PR TITLE
Remove React Live and replace with CodeSandbox examples

### PR DESCRIPTION
**Pull request by hartstinger**
Addressing issue #61 

CodeSandbox examples replicated from React Live (Code Playground component). 
Iframes placed in related `.pug` files and `.md` deleted.

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview for *react-redux-workshop* ready!

Built with commit 5030f0d612d24cc28e92b9564b850fd8490ae690

https://deploy-preview-71--react-redux-workshop.netlify.com

**Comment by hartstinger** [comment]
@DSchau -> be sure to check out the codeSandbox examples. i tried to follow the format of the React Live code examples and "hide" the main index/root attachment, but maybe that's too clever. Let me know, and I can change these back.

**Comment by DSchau** [comment]
@hartstinger I think these are great. One thing that could be worth doing is encapsulating these within the repo itself. CodeSandbox allows you to import from git, so we could use that functionality to treat our code examples _as_ code we're  in total control of.

That said, for now, this is great! Thanks!

**Comment by DSchau** [comment]
@hartstinger if you actually want to close the issue, I think you have to use a different keyword!

https://help.github.com/articles/closing-issues-using-keywords/

**Pull request merged**
