### PR TITLE
feat: add codesandbox links/tip

### LINKED ISSUE #36: Add CodeSandbox Links/Markdown file to labs
Let's add a CodeSandbox section (in Tips and Tricks) we can fall back on if stuff goes wrong day of.

### PR DESCRIPTION
**Pull request by DSchau**
Fixes #36

### CODE REVIEW

**Comment by DSchau** [comment]
Deploy preview for *react-redux-workshop* ready!

Built with commit 481807f4396b519b387da9a513a614cbdfe44279

https://deploy-preview-37--react-redux-workshop.netlify.com

**Comment by DSchau** [comment]
Deploy preview for *react-redux-workshop* ready!

Built with commit a66a70f4cd8bfd578812ad54a192ed2793a889e5

https://deploy-preview-37--react-redux-workshop.netlify.com

**Comment by meyerds** [comment]
Tests don't seem to be working in the CodeSandbox :-(

**Comment by DSchau** [comment]
@meyerds I noticed that too. It's weird, they _should_ work we're using a pretty vanilla create-react-app set up.

**Comment by DSchau** [comment]
@meyerds wonder if it's related to this?

https://github.com/CompuIves/codesandbox-client/issues/364#issuecomment-367940752

**Comment by meyerds** [comment]
@DSchau seems likely. Sounds like no fix yet though. What do you want to do for the labs? Just push for people to set up their environment as usual, for now?

**Comment by DSchau** [comment]
@meyerds yeah, I think we'll do that anyways. I suppose tests aren't _necessary_ for usage of CodeSandbox but it would've been nice.

Slack is being shitty on my computer, but if we comment out `import 'jest-enzyme';` from setupTests.js it works 🎉

**Pull request merged**
